name: Vairal Video Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 55
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python bot.py
        env:
          GROUP_ID: ${{ secrets.GROUP_ID }}
